services:
    swiftmailer.spool.smart_systems_spool:
        class: SmartInformationSystems\EmailBundle\Spool\SmartInformationSystemsEmailSpool
        arguments: ['@doctrine.orm.entity_manager']
    swiftmailer.mailer.default.spool.smart_systems_spool:
        alias: swiftmailer.spool.smart_systems_spool
